### ISSUE TITLE
no configuration file provided: not found

### ISSUE THREAD

**Issue by Peter-developer01** [LibreChat-AI/librechat.ai#25]
Hi.

According to the [manual](https://www.librechat.ai/docs/local/docker) for Docker installation, I have:

- cloned this repository
- navigated to the LibreChat directory
- created a .env file from .env.example

But on last step, when I run `docker compose up -d`, it fails:

```sh
$ docker compose up -d
no configuration file provided: not found
$
```

(I'm using bash)

**Comment by fuegovic** [comment]
You'd have more answers if you post on https://github.com/danny-avila/LibreChat than here, since here is the website repo...

You need to run the command from within the librechat directory, Also look at the content of the directory, maybe there was an error when you cloned it. That error means that docker couldn't find the `docker-compose.yaml` file in the directory where you ran that command from.

**Comment by Peter-developer01** [comment]
@fuegovic lol! Thanks. I have no idea how I got into this repo instead of the main one...
